server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:spring_practice}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:your_db_password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.i_dont_love_null.allergy_safe

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    com.i_dont_love_null.allergy_safe: INFO

jwt:
  secretKey: ${JWT_SECRET:your_jwt_secret}
  issuer: ${JWT_ISSUER:https://github.com/your-github-id}
  expirationMinute: 60

swagger:
  contact-name: ${SWAGGER_CONTACT_NAME:your-name}
  contact-mail: ${SWAGGER_CONTACT_MAIL:example@example.com}
  contact-url: ${SWAGGER_CONTACT_URL:https://example.com}
  app-name: ${SWAGGER_APP_NAME:Example App}
  app-description: ${SWAGGER_APP_DESCRIPTION:Example App Description}
  app-version: ${SWAGGER_APP_VERSION:1.0.0}
  app-license-url: ${SWAGGER_APP_LICENSE_URL:https://www.apache.org/licenses/LICENSE-2.0.html}
  app-license: ${SWAGGER_APP_LICENSE:Apache 2.0}
